const CDP='http://127.0.0.1:9222';
const t=await (await fetch(`${CDP}/json/new?about:blank`,{method:'PUT'})).json();
const ws=new WebSocket(t.webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
let id=0;const pending=new Map();let exceptions=[];
ws.onmessage=ev=>{const m=JSON.parse(ev.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);return;}
  if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params.exceptionDetails.exception?.description||'x');};
const send=(method,params={})=>new Promise(res=>{const i=++id;pending.set(i,res);ws.send(JSON.stringify({id:i,method,params}));});
const ev=async expr=>{const r=await send('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true});return r.result?.result?.value;};
await send('Page.enable');await send('Runtime.enable');
await send('Page.navigate',{url:'http://localhost:8720/#diag'});
await new Promise(r=>setTimeout(r,8000));
console.log("S keys:", await ev(`Object.keys(window.S||{}).join(',')`));
console.log("verifyPassed:", await ev(`window.S&&window.S.verifyPassed`));
console.log("parserPassed:", await ev(`window.S&&window.S.parserPassed`));
console.log("R keys:", await ev(`Object.keys(window.R||{}).join(',')`));
console.log("mc len:", await ev(`document.getElementById('mc').innerHTML.length`));
console.log("mc text:", (await ev(`document.getElementById('mc').innerText`)).slice(0,200));
console.log("exceptions:", exceptions.length);
exceptions.slice(0,5).forEach(e=>console.log(" !", e.slice(0,200)));
ws.close();process.exit(0);
